{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3961949,
          "sha512": "3abb8424a986ff5a1e952c06581955596ca917b21b9a355ca20952777b4f979ade362edf7841618d7c2633f6bae4d6c6c5028cb672b6e4ecda11c781bf8fee27",
          "sha256": "28db85b4af997a2d574e9823b89ae973beb3aac91d8535f3c3114b3674af248b",
          "sha1": "015e60e14dc2c84ea8146ab8aa72cae3fd6d1e81",
          "md5": "ac74e496f39c5bd3e5db6ad5edd858ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-b20183e04096094bcc37d9cde2a4b96f5cc684cf"
          }
        },
        {
          "group": "com.trustingsocial.trust_vision_plugin",
          "module": "trust_vision_plugin_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3961949,
          "sha512": "3abb8424a986ff5a1e952c06581955596ca917b21b9a355ca20952777b4f979ade362edf7841618d7c2633f6bae4d6c6c5028cb672b6e4ecda11c781bf8fee27",
          "sha256": "28db85b4af997a2d574e9823b89ae973beb3aac91d8535f3c3114b3674af248b",
          "sha1": "015e60e14dc2c84ea8146ab8aa72cae3fd6d1e81",
          "md5": "ac74e496f39c5bd3e5db6ad5edd858ca"
        }
      ]
    }
  ]
}
