{
  "formatVersion": "1.1",
  "component": {
    "group": "com.trustingsocial.trust_vision_plugin",
    "module": "trust_vision_plugin_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_profile-1.0.aar",
          "url": "trust_vision_plugin_profile-1.0.aar",
          "size": 74661,
          "sha512": "287249d7210fabfb9630455392062a6ef2b4c4c91ad1c38b76e8ed21fcbc59999d48b8afba5e8efe18701f46c9673d30bb1f3d8593a45ae3b62ef5b0793f04b6",
          "sha256": "b3cea4a8dfeccfcd6d79352b26c39dd538a877117771689f723a484c46c860c2",
          "sha1": "b5f2f1d1cbd1c97d1529465039e8bdd2bc892802",
          "md5": "7e7cf0a679c8c483429d4d969b707edc"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-cdbeda788a293fa29665dc3fa3d6e63bd221cb0d"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "com.trustvision",
          "module": "tv_sdk",
          "version": {
            "requires": "3.1.3.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tv_sdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "trust_vision_plugin_profile-1.0.aar",
          "url": "trust_vision_plugin_profile-1.0.aar",
          "size": 74661,
          "sha512": "287249d7210fabfb9630455392062a6ef2b4c4c91ad1c38b76e8ed21fcbc59999d48b8afba5e8efe18701f46c9673d30bb1f3d8593a45ae3b62ef5b0793f04b6",
          "sha256": "b3cea4a8dfeccfcd6d79352b26c39dd538a877117771689f723a484c46c860c2",
          "sha1": "b5f2f1d1cbd1c97d1529465039e8bdd2bc892802",
          "md5": "7e7cf0a679c8c483429d4d969b707edc"
        }
      ]
    }
  ]
}
